### ISSUE TITLE
Some comics do not show cover as first page

### ISSUE THREAD

**Issue by theotocopulitos** [mcpierce/comixed#122]
After adding several books to the library, the cover presented is not the real cover. Opening the book within comixed shows all pages, and they are not properly ordered.

See Screenshots:

1) Main colection page with comics not showing proper comic

2) Details page for the first comic in (1) shows, again, wrong cover

3) Pages details shows wrong page ordering: page "X-Men Blue (2017-) 031-000.jpg" (cover) is shown, for example after page "X-Men Blue (2017-) 031-014.jpg, and according ot image (2), the file used as a cover is "X-Men Blue (2017-) 031-004.jpg"

Screenshots taken using this comic file: "X-Men Blue 031 (2018) (Digital) (Zone-Empire)"

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Browser : chrome

Image #1
![screenshot 1](https://user-images.githubusercontent.com/1540135/43222891-b01f5730-9051-11e8-8a98-db4e1b5b0a30.png)

Image#2
![screenshot 2](https://user-images.githubusercontent.com/1540135/43222889-afe3cc56-9051-11e8-9665-82b118edf75b.png)

Image#3
![screenshot 3](https://user-images.githubusercontent.com/1540135/43222890-b003536e-9051-11e8-9193-e337f71fd920.png)

**Comment by mcpierce** [comment]
For the comic in the screen shots above, can you share the list of pages within the comic?

By default, pages should be added to the database in alphabetical order (the import assumes pages have filenames that end with their order number). 

I have a few comics that have ad pages that can sometimes get sorted to the front due to alphanumeric sorting.

**Comment by theotocopulitos** [comment]
You can see, clearly from pictures 2 and 3 that the names are correct in the file, the cover being xxxx-000.jpg, but it is sorted as the fourth last one, just after xxxx-022.jpg

The files are:

01/07/2018  01:01         2.439.127 X-Men Blue (2017-) 031-000.jpg
01/07/2018  01:01           905.182 X-Men Blue (2017-) 031-001.jpg
01/07/2018  01:01         1.481.246 X-Men Blue (2017-) 031-002.jpg
01/07/2018  01:01         1.118.643 X-Men Blue (2017-) 031-003.jpg
01/07/2018  01:01         1.543.692 X-Men Blue (2017-) 031-004.jpg
01/07/2018  01:01         1.420.514 X-Men Blue (2017-) 031-005.jpg
01/07/2018  01:01         1.449.945 X-Men Blue (2017-) 031-006.jpg
01/07/2018  01:01         1.331.338 X-Men Blue (2017-) 031-007.jpg
01/07/2018  01:01         1.490.422 X-Men Blue (2017-) 031-008.jpg
01/07/2018  01:01         2.008.922 X-Men Blue (2017-) 031-009.jpg
01/07/2018  01:01         2.122.822 X-Men Blue (2017-) 031-010.jpg
01/07/2018  01:01         1.806.640 X-Men Blue (2017-) 031-011.jpg
01/07/2018  01:01         1.389.232 X-Men Blue (2017-) 031-012.jpg
01/07/2018  01:01         1.916.349 X-Men Blue (2017-) 031-013.jpg
01/07/2018  01:01         1.728.475 X-Men Blue (2017-) 031-014.jpg
01/07/2018  01:01         1.429.679 X-Men Blue (2017-) 031-015.jpg
01/07/2018  01:01         1.502.621 X-Men Blue (2017-) 031-016.jpg
01/07/2018  01:01         1.772.530 X-Men Blue (2017-) 031-017.jpg
01/07/2018  01:01         1.398.688 X-Men Blue (2017-) 031-018.jpg
01/07/2018  01:01         1.785.462 X-Men Blue (2017-) 031-019.jpg
01/07/2018  01:01         1.577.076 X-Men Blue (2017-) 031-020.jpg
01/07/2018  01:01         1.762.412 X-Men Blue (2017-) 031-021.jpg
01/07/2018  01:01         1.937.999 X-Men Blue (2017-) 031-022.jpg

If it is of any use, the file is here

https://drive.google.com/file/d/1QLVxo98te4PZRofD_72ccO-Z2tcAjZPS/view?usp=sharing

**Comment by mcpierce** [comment]
So I believe I've solved this. I refactored how the comics are initially loaded into the library. The archive loaders now get the list of filenames, sort them alphabetically, then creates the pages in alphabetical order. The X-Men comic above loads and displays in the desired order now.
