### ISSUE TITLE
Make pages that show comic covers consistent

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#184]
As a library owner, I want to have a consistent experience when viewing pages of comics. I shouldn't have to learn a different way to interact with the comics on each page.

The **Import**, **Duplicate Pages** and **Library** views should all have the same UX experience. They should show consistent cover views with the same details in the overlays.

**Comment by jrft1379** [comment]
I guess I don't understand the purpose of the "Duplicate Pages" view. I'd rather see a "Duplicate Books" view. But I agree a consistent UI is important.

**Comment by mcpierce** [comment]
> 
> 
> I guess I don't understand the purpose of the "Duplicate Pages" view. I'd rather see a "Duplicate Books" view. But I agree a consistent UI is important.

This view shows you pages that are identical in more than one book. The example that comes to mind for me is the scanner ads. By showing them this way it makes it easier to decide what to do with them; i.e., in my case I would mark them as blocked and then delete them from the books containing them.

**Comment by mcpierce** [comment]
With the move to PrimeNG for the front end, this is no longer an issue.
