### ISSUE TITLE
Mapped drives not seen by ComiXed

### ISSUE THREAD

**Issue by Krandor1** [mcpierce/comixed#195]
Basically on windows if a drive is mapped to the OS (like X:\ pointing to \\server\comics), the JVM that comixed is running in is not able to pull data from X:\. The logs show nothing like it just determines it is an invalid drive and exits. 

Using the UNC in place of the drive letter works.

**Comment by mcpierce** [comment]
@Krandor1 Can you verify, with the latest release, that this is still an issue? I'm unable to replicate it with the current code. If not, would you please close this ticket? Thanks.

**Comment by bareheiny** [comment]
Just adding my two cents.

My comics are stored on a USB drive connected to a PC.  I run CX on the PC, and also on a Sufrace - which maps to the PCs USB drive.

I haven't had any connection issues with either setup.
