### ISSUE TITLE
Add tabbing to the comic details view page

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#205]
As a comic reader, I would like to have all of the details for a comic grouped together. This would make it easier for me to focus on the details I'm interested in without cluttering the screen.

The accomplish this, the comic details view should be moved to a tabbed view. The tabs will be:
 * **Overview** - Shows them series, volume, issue #, title, story arc, publisher, publication date, date added to the library, summary, read status
 * **Story** - Shows the summary, description, characters, locations, teams and story arcs details.
 * **Credits** - Shows the creator credits, publication date, publisher name.
 * **Pages** - Shows the pages for the comic.

**Comment by jrft1379** [comment]
May I suggest a few changes to this? I know everyone is different, but these are how I would want to see info grouped:

**- Overview:** Series, Sort Name, Volume, Issue #, Story Title, Story Arc, Arc #, Publisher, Imprint, Publication Date, Release Date, Scan Type
**- Story:** Summary, Description, Characters, Teams, Locations, Story Arc Details
**- Credits:** Creator Credits
**- Pages:** Pages and Page Types

**Comment by mcpierce** [comment]
> 
> 
> May I suggest a few changes to this? I know everyone is different, but these are how I would want to see info grouped:
> 
> **- Overview:** Series, Sort Name, Volume, Issue #, Story Title, Story Arc, Arc #, Publisher, Imprint, Publication Date, Release Date, Scan Type
> **- Story:** Summary, Description, Characters, Teams, Locations, Story Arc Details
> **- Credits:** Creator Credits
> **- Pages:** Pages and Page Types

I tweaked the fields to reflect your feedback. Some fields you mention (imprint, arc #, scan type) aren't currently fields in the database.
