### ISSUE TITLE
The Edit Comic Data layout is uneven

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#220]
**Describe the bug**
The cover for the actual comic feels too high and the actual scraped candidate feels too low in the overall layout.

Instead, these should all feel level across the page.

To fix it, we could:
 * move the issue title above the cover image,
 * move the issue subtitle below the cover into the box with the **Read** button,
 * move the **Showing # Of #** title up one row to be level with the other titles, and
 * move the issue selection dropdown to below the scraped cover to line up the covers.

**Screenshots**
![screen shot 2018-10-07 at 12 23 16 pm](https://user-images.githubusercontent.com/61601/46584029-a2975a80-ca2c-11e8-95e2-92591fbb9ab4.png)

**Comment by theotocopulitos** [comment]
I'd add that you do not need that the scrapped cover sample be as big as the comic cover... also, it takes for ever to load...

**Comment by mcpierce** [comment]
Yeah, the speed is due to comicvine.gamespot.com being the source for the image. Right now the code fetches the URL for the cover image for each volume and then uses the URL returned (appending the user's ComicVine API) when it updates the HTML.

I would definitely like to cache the covers, but have not invested the time yet in what the would look like; i.e., where to keep the images, how to reference them in the database, etc. Pulling down a ton of cover images on the backend would be equally slow and could get the user's CV key locked for a period if CV decides they're "abusing the system".
