### ISSUE TITLE
Information alerts should disappear after a short time

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#230]
The information alerts can clutter up the page. Since they don't require acknowledgement, informational alerts should timeout after a short time and disappear.

## Acceptance Criteria
1. When an alert is shown, it should display for a small amount of time (about 5-15 seconds) before closing automatically.
1. If the user clicks on the close button for the alert, it is closed immediately.

**Comment by awe247** [comment]
Hi, I thought I had a fairly straight forward approach to achieve this and so I took a shot at it. It's not strictly angular so if it's not what you had in mind, feel free to reject. It's just using setTimeout/clearTimeout with a 5 second value.

**Comment by mcpierce** [comment]
> Hi, I thought I had a fairly straight forward approach to achieve this and so I took a shot at it. It's not strictly angular so if it's not what you had in mind, feel free to reject. It's just using setTimeout/clearTimeout with a 5 second value.

That's more or less what I was thinking about for this. I'll take a look now.
