### ISSUE TITLE
[DISCUSSION] Sort Name for comics

### ISSUE THREAD

**Issue by jrft1379** [mcpierce/comixed#240]
I'd like to see comics be able to be sorted by a different name than the display name. There are times when series are renamed, but are still the same series. Having a series collected in one place is always nice.

The example I like to use are the various Firestorm series. The first series was Firestorm: the Nuclear Man. The second series started out as Fury of Firestorm, before becoming Firestorm: The Nuclear Man, then ending as Firestorm. the third series started out as Firestorm, but became Firestorm: The Nuclear Man. The fourth series was The Fury of Firestorm: the Nuclear Men before becoming Firestorm: The Nuclear Man.

As you can see, that is confusing.

by introducing a "Sort Title" it would allow all of these titles to be display their actual name, but sort as "Firestorm v1" "Firestorm v2" etc.

It would also allow series that start with "the" or "a" to be sorted by their bibliographic name.

I would suggest that an issue default to it's title unless the "sort title" field has a value.

Plex has this feature, and I've included a screenshot so you can see what I'm talking about.
![plex-sort-title](https://user-images.githubusercontent.com/44160767/46975971-0c031300-d096-11e8-94e7-af893f1af73a.jpg)

**Comment by mcpierce** [comment]
Yeah, this would also be similar to how iTunes has a sorting field for audiobooks so that you can group books together even though their titles might be disparate. I like it.

This is a field that would be manually entered after scraping, yeah? I'm not sure of an analogous field in the ComicVine APIs that could be used.

**Comment by jrft1379** [comment]
Yeah, I would say its manual. Like I said, it would sort by the "Title" field unless there is a value in the Sort Title" field. Alternatively, you could have it automatically copy the Title from ComicVine into both fields.

**Comment by mcpierce** [comment]
Closing this as completed in #241.
