### ISSUE TITLE
Format field

### ISSUE THREAD

**Issue by jrft1379** [mcpierce/comixed#244]
This would be another field that would be manually entered for books that aren't of standard format. It could either be enter your own or a drop down menu, or a combination.

If it's a drop down, I'd like to see the following formats included:
Trade Paper Back
Graphic Novel
Deluxe Edition
Treasury
Digest
Preview
Promotional
Unpublished
Book
Magazine
Manga (is it possible that if this is selected it toggles a "read right to left" option?)

**Comment by mcpierce** [comment]
I would say for Manga to have two separate entries: "Manga (Left Oriented)" and "Manga (Right Oriented)".

**Comment by jrft1379** [comment]
That makes sense too.

One I would request NOT to have is Annual. I don't know about anyone else, but that option in ComicRack annoys me to no end.

Also, I'd like it to default to no selection automatically and allow us to enter it in manually (or read it from the file's .info if like me, you've already placed it there).

**Comment by jrft1379** [comment]
Same is true for "Giants" or "80-Page Giants" and the like.
