### ISSUE TITLE
Imprint Field

### ISSUE THREAD

**Issue by jrft1379** [mcpierce/comixed#245]
I'd like to see an imprint field. This is especially important for publishers like DC (who has Vertigo, Wildstorm, Milestone, etc. under it's umbrella) and Image (Top Cow, Skybound, etc.).

**Comment by mcpierce** [comment]
In the scenario of DC and Vertigo, which would be the value for the comic's publisher and which would be the value for the comic's imprint? In looking in CV's data, Vertigo, Wildstorm, etc. appear to be first-class publishers with no mention of a parent company. Here's an example of the results from a query for Wildstorm:

![image](https://user-images.githubusercontent.com/61601/47017072-4c5aa380-d11f-11e8-8228-0c5ead2a90af.png)

**Comment by jrft1379** [comment]
I'd say DC is still the publisher. I _think_ ComicRack Scraper has an if/then for Vertigo and the like: If the publisher comes back as Vertigo, then it knows Vertigo is the imprint and DC is the publisher. I know it means writing individual rules for each imprint. Fortunately, there aren't a lot of imprints out there.

**Comment by mcpierce** [comment]
Okay, fair enough. We'd then want to have some knowledge in the scraper code to know that, for certain Publishers, they're actually an imprint for another Publisher. 

(checks CVS code)

[Here](https://github.com/cbanack/comic-vine-scraper/blob/master/src/py/database/comicvine/cvimprints.py) I see where CVS did the above. They specifically match publisher's by name and looks like a pretty easy way to accomplish this.
