### ISSUE TITLE
"All Cover Thumbnails Are the Same Size" option

### ISSUE THREAD

**Issue by jrft1379** [mcpierce/comixed#246]
I like that in ComicRack I can choose to have all comics have the same thumbnail size. Without this option, covers that are larger or have wraparounds have 2 options:
1. have the larger cover show, thus creating a visual inconsistency
2. create a second cover for the front page that crops size for the sake visual consistency.

I'd also like to see it automatically look at the cover from the right of the image, that way if it does crop, it will crop to the front cover of a comic.

Let me know if this makes sense and I'll provide screen shot examples.

**Comment by mcpierce** [comment]
Yeah, a visual would help me to follow what you're saying. Right now we support the slider on the library page to choose the size for the cover display card.

**Comment by jrft1379** [comment]
In the first one, you can see the sizes of all the issues are the same size (no matter how large you scale them the ratio is constant).

In the second one, you can see the cover that is a wrap around is visually larger and thus breaks up the uniformity of the cards. If this is the only option, the solution is to create a second cover image that is a crop of the part of the cover you want to display and put it at the front of the book to display as the cover.

The third image shows where in ComicRack you can find this option so if you want to see it work for yourself, you can.

![covers - uniform size](https://user-images.githubusercontent.com/44160767/47017976-a3617800-d121-11e8-8a04-4b38e45201dc.jpg)
![covers - ununiform size](https://user-images.githubusercontent.com/44160767/47017977-a3617800-d121-11e8-9320-9c601247e0ce.jpg)
![option toggle](https://user-images.githubusercontent.com/44160767/47018250-5e8a1100-d122-11e8-9072-0aa40dd0be3b.jpg)

**Comment by mcpierce** [comment]
Ah, I see what you're pointing out.

Right now the sizing targets making the covers all fit into a grid. One possibility could be, if such an option were set, to show the covers all at the same height and let any that overflow their view be cropped at the edge of the view.

I would definitely like to get @awe247 to weigh in on how he would approach this.

**Comment by awe247** [comment]
> I would definitely like to get @awe247 to weigh in on how he would approach this.

I like this as an option. I think in practical terms there are a number of ways you can clip an image in css, especially when you know you are dealing with a fixed height:width ratio.

I think in most cases where cropping is occurring you would prefer to see the right-most part of the image (given the example above anyway). That might be a challenge. I'm pretty sure this can be done, but can't recall the specifics or cross-browser support.

Plans for thumbnail caching should probably be taken in to account also.

**Comment by jrft1379** [comment]
Thumbnail caching is a concern of mine. ComicRack has become unbelievably slow due to the shear number of thumbnails it caches for me (I have 54,000 books indexed). In fact, it can't even keep up with the amount I have - it is constantly refreshing and can't remember when I've set a particular issue as the top of a stack.

**Comment by mcpierce** [comment]
I've been thinking about caching for a while as well. Right now, when CX shows you a page, it has to open the comic archive, extract the image and send it back to the browser. Which is, of course, pretty slow.

This is definitely a topic for another discussion issue to plan the caching feature so we get it right. I've some ideas for an efficient one using non-computed unique fields from a comic to quickly retrieve a cached image from the filesystem instead of going to the archive.

**Comment by mcpierce** [comment]
In reworking the way that comics are displayed on various pages (library page, publisher page, series page, etc.) I've added a checkbox to the view toolbar. What it does is let the user choose to apply the cover size value to either the width or the height of all covers equally. 

So, for example, if you have a wraparound cover and use the slider for cover widths (deselect the checkbox), your covers would look like this:

<img width="1097" alt="screen shot 2019-02-10 at 10 04 36 pm" src="https://user-images.githubusercontent.com/61601/52544649-f5d53d00-2d7f-11e9-9fc0-35833c81f1a2.png">

If you use it instead for the heights (select the checkbox), the covers would look this:

<img width="1099" alt="screen shot 2019-02-10 at 10 04 50 pm" src="https://user-images.githubusercontent.com/61601/52544665-130a0b80-2d80-11e9-98cc-643eb2f0447d.png">

Would that meet this feature request?

**Comment by mcpierce** [comment]
@jrft1379 Could you take a look at a recent sanity build and see if the above mentioned feature meets your requirement? And, if so, please close this ticket. Thanks.

**Comment by mcpierce** [comment]
Marking this as closed.
