### ISSUE TITLE
No save button

### ISSUE THREAD

**Issue by jrft1379** [mcpierce/comixed#260]
**Describe the bug**
No button to save changes manually made to metadata.

**To Reproduce**
1. Go to an issue
2. Click on "Edit data"
3. try and save changes made, and there is only a "fetch" or a "cancel" button.

**Expected behavior**
Be able to save changes manually made

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/44160767/47358466-c21ebc00-d697-11e8-9af6-92cee0ebd723.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.67 (Official Build) (64-bit)

**Comment by mcpierce** [comment]
## Acceptance Criteria:
1. Add a new REST endpoint that accepts a JSON object with the following fields:
 * comic_id
 * series
 * volume
 * issue_number
1. Add a **Save** button to the edit display.
1. If the **Save** button is clicked:
   1. Call the new REST API.
   1. Update the comic's details in the browser
1. If the **Cancel** button is clicked:
   1. Restore the values for the comic in the displayed fields.
