### ISSUE TITLE
[DISCUSSION] Where is .jar file?

### ISSUE THREAD

**Issue by cwsleeper** [mcpierce/comixed#297]
I recently read about this app on ComicRack and would love to use it. My problem is I am not a developer and the instructions say to run the .jar file from the command line. I have downloaded the .zip file, opened it and there is no .jar file. Would you kindly help this noob in opening the application?

**Comment by cwsleeper** [comment]
Thanks. Sorry about the late response. I had a Java RE mismatch that made me learn that I don't like learning about Java in Mac. Able to open now and marking the issue closed.

**Comment by cwsleeper** [comment]
Thanks for the response. Is there a place to ask questions? I am importing right now and have a library of over 24,000. Selecting all and trying to import produces an error. Is there a known limit for import? I am doing it in chunks right now, but of course that will be onerous.

Thanks again.

Coleman

**Comment by mcpierce** [comment]
You can ask questions here in the **Issues** section.
