### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by shpanky73** [mcpierce/comixed#305]
**Describe the bug**
I've downloaded the code and placed in a folder called comixed on my desktop pc.  I then navigate to that folder  and attempt the  command to run it "java -jar comixed-app-*.jar"

I get the response: 
Unable to access jarfile comixed-app-*.jar

I do not see this file anywhere in any of the directories.  Am I doing something wrong?

**Comment by mcpierce** [comment]
In what directory did you download the JAR file? Also, you'll need to use the full filename and not include the asterix. So, if you downloaded the file **comixed-app-0.2.9-SNAPSHOT-20181118210154.jar** into your **Downloads** directory, you'll want to go there and type:

```
java -jar comixed-app-0.2.9-SNAPSHOT-20181118210154.jar
```

**Comment by shpanky73** [comment]
I'm a dummy, used to python repositories and downloaded the raw code.  I found the jar files on the releases tab at top and not in the drop down.  Sorry!

**Comment by mcpierce** [comment]
No problem. If you're able to run things, then please close this ticket out. I look forward to hearing your feedback and ideas.

**Comment by shpanky73** [comment]
Closing now.  Thanks!
