### ISSUE TITLE
Unable to launch comxed

### ISSUE THREAD

**Issue by shpanky73** [mcpierce/comixed#308]
**Describe the bug**
Downloaded the latest jar file and attempted to launch (with latest version of java).  I've added the log to this bug.   Let me know if you need more details.
[comixed_issue.txt](https://github.com/mcpierce/comixed/files/2596882/comixed_issue.txt)

**Comment by mcpierce** [comment]
Did you run another version of ComiXed previously? If so, I believe that's the problem based on this:

> Caused by: org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 1.0
> -> Applied to database : 1242390701
> -> Resolved locally    : -1499226911

There's an issue with the database migrations from 0.1 to newer versions, and the only way to work around it is to delete the .comixed directory in your home directory (c:\users\YOURNAME\.comixed on Windows, or ~/YOURNAME/.comixed on *nix and Mac) and re-run the newer version of the application. The existing library will get lost, but the database will be reset.

**Comment by shpanky73** [comment]
Ahhh i did run an earlier version and had a database issue.  This resolved my problem.  Closing ticket, thank you.
