### ISSUE TITLE
Mini display representation of full page.

### ISSUE THREAD

**Issue by Skullberry9000** [mcpierce/comixed#384]
Mini display representaion of full page. While reading a comic in ComicRack and zoomed in on a page there is a mini version that appears when you move or scroll on the page that you are reading. The mini page shows you the part of the full page that you are reading. The parts of the full page that you cannot see while zoomed in are grayed out on the mini page. This way you can see if you are viewing the entirety of any given panel without having to zoom all the way back out then back in. hoping the new reader has this feature.

**Comment by Skullberry9000** [comment]
[https://mojorisingza.files.wordpress.com/2010/07/comicrack-double-page-zoomed-with-overlay.jpg](url)

[https://mojorisingza.files.wordpress.com/2010/07/comicrack-single-page-zoomed.jpg](url)

[https://mojorisingza.files.wordpress.com/2010/07/comicrack-double-page-view-zoomed-with-overlay.jpg](url)

**Comment by mcpierce** [comment]
At this point in time, I've been considering phasing out the browser-based reading of comics. I think ultimately ComiXed would serve a better purpose as a library management tool and avoid competing with the feature sets of fully formed readers.
