### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rainerc** [mcpierce/comixed#397]
I cannot get ComixEd running. Tried on 2 different machines.

**To Reproduce**
1. Installed latest JAVA release 1.8.0_201
2. Downloaded comixed-app-0.3.0.jar
3. Doubleclicked comixed-app-0.3.0.jar and Java is starting according to task manager
4. Nothing else is happening. Did I miss something?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge, IE

**Comment by mcpierce** [comment]
ComiXed is a browser-based application. After you've launched it, you would need to then point your browser to ```http://localhost:7171``` to access the application.

To ensure things are running, I would suggest the first time you run it to launch the app from the command line:
```
    java -jar comixed-app-0.3.0.jar
```

It will show you output and let you see if any errors occurred while starting.

Please try that and, if it works for you, mark this ticket as closed.

**Comment by rainerc** [comment]
Thanks for your reply! I was able to run comixed in Chrome. But now nothing happens when I click on "Comics -> Library" or "Comics -> Import". Besides: Do I have to use the "Login" button? If yes: with which credentials?

**Comment by mcpierce** [comment]
Yes. The credentials are in the "Interacting With The Application" section of the [read me file](https://github.com/mcpierce/comixed/).

**Comment by rainerc** [comment]
This did it, thanks a lot! Also big thanks for the readme.

**Comment by mcpierce** [comment]
> This did it, thanks a lot! Also big thanks for the readme.

You're welcome. :D
