### ISSUE TITLE
.git directory is not found!

### ISSUE THREAD

**Issue by azuravian** [mcpierce/comixed#437]
**Describe the bug**
When trying to install using `mvn clean package`, I get the following error:
`[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project comixed-library: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]`

I noticed during the install, the instruction to install Angular 7 was "npm install -g @Angular@7.2.0"  This resulted in an the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for angular@7.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I had to use "npm install -g @Angular/cli@7.20" in order to install 7.2.0.

**To Reproduce**
1. Follow installation instructions
2. Run `mvn clean package`
3. See error

**Expected behavior**
Installation would complete successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome or Vivaldi
 - Version: 0.4?

![2019-04-09 18_40_09-Command Prompt](https://user-images.githubusercontent.com/7379812/55839744-f9beda80-5af6-11e9-8aa0-d693a5de1cc5.png)

**Comment by mcpierce** [comment]
For the first part, did you clone the git repository or do something else to get a codebase? The .git directory is created as a part of that process.

For the second part, I don't think we need to install Angular at the global level; i.e., so long as you have yarn npm and yarn then that will pick up Angular when you build locally. I'll strike that step from the readme file.

**Comment by azuravian** [comment]
That worked thanks.
