### ISSUE TITLE
Remember login credentials

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#454]
As a user I would like the option for CX to remember my login credentials so I don't need to re-enter them each time I open the interface.

**Comment by mcpierce** [comment]
That's not a function of the web application, but of your browser.

**Comment by bareheiny** [comment]
Hmmm, I'll need to check into that.

I'm not seeing the option to remember passwords - and that's only in CX.  Edge asks about near every other site.

**Comment by mcpierce** [comment]
I wonder if it might not be because it's using localhost as the hostname?

On Firefox and Chrome, I'm able to double-click on the email field and the browser will remember and fill in the field for me.

**Comment by bareheiny** [comment]
Looks like the issue is Edge being Edge.

I had it working, and now it's not.  Opera had no issues at all.  Methinks it may be time to go back to Chrome.
