### ISSUE TITLE
ComicRack import does not appear to be working

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#459]
Running the comixed-importer does not result in comics being added to CX.

Initially, the CR ComicDB.xml was generated on a different machine than CX is running on (this meant that the file paths would be different).  This resulted in errors on each file (no log was output for this run).

Subsequently, I installed CR on the same machine as CX, added four comics and exported the database, and ran the import jar again.

The output log (using --logging.level.org.comixed=DEBUG > g:\CRImport.log) shows the comic files are being processed and various bits of metadata are being extracted, however after the process is run the comics are not in CX.

Deleting the CX db, and restarting CX creates a new DB sized 64b.  Running the import jar does not increase the file size, despite the log containing messages saying "Saving comic to database".

**Comment by mcpierce** [comment]
Were you able to verify if any entries were added to the comixed.mv.db file? You can download the [H2 command line tools](https://www.h2database.com/html/download.html) and run them to open the database file and see if any records were inserted. It may not grow the file for only a handful of entries, since H2 pre-allocates some space.

Or you could zip the files together and attach them to this ticket and I can look at them.

**Comment by bareheiny** [comment]
After getting H2 set up (and figuring out how to use it), I deleted comix.mv.db and started from scratch again.

According to H2, there are no records in comix.mv.db after running what looks like a successful import (according to the log).

I loaded a comic via the CX import page, and re-queried the DB just to be sure I wasn't missing something - H2 is showing the record.

**Comment by mcpierce** [comment]
Okay, I see what you're describing. I'll see if I can reproduce it here and figure out the issue.

**Comment by mcpierce** [comment]
I believe this is fixed now. Be sure, when you run the importer, that your replacement **exactly** matches the root path in the ComicDb.xml file. The replacement rules are necessarily case sensitive.

See the README.md file in the comixed-importer submodule for details.

**Comment by bareheiny** [comment]
I'll see if I can test this tonight.  May be a few days though as I'll need to set everything up on another machine - my main one is currently importing (estimate it'll finish the current batch of 10k in around 17 hours).

**Comment by mcpierce** [comment]
Understood. I'm also right now tweaking our CI/CD environment to build both develop and release branches so you can get a proper build to use.

**Comment by bareheiny** [comment]
Just as an FYI, I'm averaging 10.8 imports per minute - using that to guesstimate the completion time for my current import.

For comics with under 51 pages, the rate is about 13.  It drops to 7 for 51 to 100 pages.

I'll document everything once I finish up - I'm thinking that it may be useful to give users expected times for imports to complete.  CR is pretty quick, but CX does more during the import....if a user doesn't see a quick import, it may turn them off CX initially.

**Comment by bareheiny** [comment]
CMD window showed an out of memory error (same as #480) after loading 8 out of 31 comics via the importer.

**Comment by bareheiny** [comment]
Ran the jar with "-Xmx2g", import was successful.

Specifically, there were no errors thrown that I could see, and a number of comics were loaded.  I have not checked to see if any were missed.
