### ISSUE TITLE
no import button on fresh install

### ISSUE THREAD

**Issue by RangerRick** [mcpierce/comixed#468]
**Describe the bug**
I'm trying comixed for the first time. I log in as the default admin, and attempt to import my comics, and there is no import button on the import page.  I have reproduced this on Chrome, Firefox, and Safari.

**To Reproduce**
1. Log in
2. Go to admin -> import
3. Configure a path with comics
4. Click `Find Comics`

**Expected behavior**
A button to import the comics.

**Screenshots**
<img width="1680" alt="no import button" src="https://user-images.githubusercontent.com/89252/58727727-1cf95e00-83b3-11e9-9c79-36e7d14a12fb.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Firefox
 - Version 67

**Additional context**
latest available snapshot: `comixed-app-0.3.9-SNAPSHOT-20190518205152.jar`

I also tried 0.3.0 and while it didn't exhibit this problem, it froze on import and never completed.

**Comment by mcpierce** [comment]
Hi, thanks for reporting this.

The import button was removed during development for our 0.4 release. The new method is:
1. select comics by clicking on their covers,
2. right-click on any cover to show a popup menu, then
3. click the import menu item.

Unfortunately the Travis build environment is broken (the code builds on different machines locally, but not on Travis for some reason), so this new code isn't in a build.

The latest build, the on in your screenshot above, has a sidebar that shows your selections. If you go to the **Library** menu and click the **Selections** menu item, it'll show the selections sidebar. Then you can click the import button to import those comics.

Sorry for the long description. I'm trying to get all of the selection actions down to consistently using the popup menu and we're right now in the middle of that work.

For the last comment above about freezing, please open a separate issue to discuss that. But first be sure you left the system run for some period of time. The import isn't optimal yet and, depending on how many pages and how they're stored in the archive, can take a while to import. We've got that in the plans for our next release to fix.

**Comment by mcpierce** [comment]
@RangerRick The Travis CI environment is fixed, and there should be a build generated shortly that includes the changes I described above. Please take a look at that and, if you're able to do the import, please close this ticket. Thanks!

**Comment by RangerRick** [comment]
Hrm, I tried to verify this but when I launch the new build I get a 404 hitting `/` or `/import` in the web UI.  I'm assuming this is the same problem as #469.

**Comment by mcpierce** [comment]
@RangerRick Yeah, apparently the work I did for #465 seems to have introduced another bug (reported in #469) with the deliverable that's created. I'm going to have to fix that, and then I'll reply here to let you know when you can verify the bug.

**Comment by mcpierce** [comment]
@RangerRick I believe I've fixed the 404 error now as well. Please check out the build and, if it works, feel free to close this ticket.

**Comment by RangerRick** [comment]
No 404, but now I get a new issue (in the JS console) when I click `Find Comics`:

```
ERROR TypeError: "action.payload.library_state is undefined"
    libraryReducer library.reducer.ts:130
    combination store.js:113
    reduceState store.js:401
    RxJS 18
    next store.js:45
    next store.js:476
```

**Comment by mcpierce** [comment]
I recommend deleting the comixed database on your system and restarting. The previous bug may have, for some reason, left it in a bad state. If it still does it after, please open another bug for it.

I think we can close this bug now, though. One down, one new one to go. 😄
