### ISSUE TITLE
404 errors when attempting to use the two latest snapshots.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#469]
As per subject.

When I try to run either 0.3.9-SNAPSHOT-20190602161109 or 0.3.9-SNAPSHOT-20190602160508, I get a 404 error when attempting to connect via Opera or Edge.

The previous snapshot runs fine, and the same command is used to start each file.  All jars are downloaded when attempting to use a new snapshot.

**Comment by mcpierce** [comment]
Okay, I'll look into this shortly.

**Comment by mcpierce** [comment]
The issue appears to be that the comixed-frontend.jar file doesn't contain the artifacts for that submodule.
