### ISSUE TITLE
Unit test failed : Adaptor Invalid date

### ISSUE THREAD

**Issue by BRUCELLA2** [mcpierce/comixed#479]
**Describe the bug**
When I package the project, one unit test failed. 
I got this message : 

Test set: org.comixed.library.adaptors.FilenameScraperAdaptorTest

Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.964 s <<< FAILURE! - in org.comixed.library.adaptors.FilenameScraperAdaptorTest
testExecuteRuleset1(org.comixed.library.adaptors.FilenameScraperAdaptorTest)  Time elapsed: 0.021 s  <<< ERROR!
org.comixed.library.adaptors.AdaptorException: Invalid date: May, 2018
	at org.comixed.library.adaptors.FilenameScraperAdaptorTest.testExecuteRuleset1(FilenameScraperAdaptorTest.java:94)
Caused by: java.text.ParseException: Unparseable date: "May, 2018"
	at org.comixed.library.adaptors.FilenameScraperAdaptorTest.testExecuteRuleset1(FilenameScraperAdaptorTest.java:94)

I'm french and my pc is in french local. I think it's the problem. In the test, the string for the date to parse is in english and is unparseable

**To Reproduce**
1 - set locale to french
2 - run the unit test testExecuteRuleset1 in FilenameScraperAdaptorTest

**Expected behavior**
No error are expected.

**Desktop (please complete the following information):**
 - OS: Linux MInt 19
 - Browser Vivaldi (Chrome)
 - Locale : French

**Comment by BRUCELLA2** [comment]
I think there is 2 options to fix this bug : 
1 -  Add the locale to use in the unit test
For example : Mockito.verify(comic, Mockito.times(1)).setCoverDate(new SimpleDateFormat("MMMMM, yyyy", Locale.US).parse(COVER_DATE_1));
And add the local in the tested method too 
For example : this.dateFormat = new SimpleDateFormat(dateFormat, Locale.US);
2 - make the string use for the date in test with the locale of the user. If the pc is a french pc, the date will be "Mai, 2018", if it's an english pc, the date wil be "May, 2018"

**Comment by mcpierce** [comment]
That's an interesting scenario. I hadn't thought about internationalization when comes to the filename scraper. It also has repercussions with the (future) library consolidation; i.e., if someone chooses to consolidate their library and uses a file naming convention that includes the month, which language (English or the local system) should it use?

For simplicity, I'd opt for using English to simplify things. Thoughts?

**Comment by BRUCELLA2** [comment]
I'm agree to simplify things, using only English it's better.
However, wouldn't it be possible to try to parse the month in English and if it doesn't work try in the local language?
When we parse the date in English, we could catch the ParseException and then try to parse it in the local language. 
So if the user uses English it works. If the user uses his language, it works. And finally if the user has already used English and wants to change to using his language for new comics, it also works.

**Comment by mcpierce** [comment]
Or perhaps use local first then fallback to English?

**Comment by BRUCELLA2** [comment]
Yes, it's better to use local first then fallback to English :)

Le mar. 25 juin 2019 à 21:39, Darryl L. Pierce <notifications@github.com> a
écrit :

**Comment by mcpierce** [comment]
I've added changes to the filename parser to try first the default locale and then the US locale before failing to parse a filename. If that works, then you can close this ticket, SVP.

**Comment by BRUCELLA2** [comment]
It's ok. No error now
I close the ticket.
