### ISSUE TITLE
Users can download all comics in a reading list.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#491]
As a user, I would like to be able to download all comics on a reading list with a single interaction (so not downloading each issue individually).

Ideally, comics would be stored locally and named in a way that allows them to be sorted in the reading list order.  The name of the file shouldn't matter much, as any decent reader will allow the use metadata as well as the filename.

This would allow me to have access to an offline library for when access to CX is not possible (I'm away from home with no wifi etc.).

**Comment by mcpierce** [comment]
Is the intent here to have CX create a downloadable archive of the set of comics for the reading list? Or is this more like when using a reader like Chunky having it download everything for the current set of comics being viewed?

**Comment by bareheiny** [comment]
More like the Chunky option I think.

There aren't many readers for Windows that support OPDS (I've been able to find one...and it hasn't been updated recently), so being able download / copy comics would provide an alternative, as well as catering for instances where network access isn't available, and CX is running on a remote machine (which is pretty much my setup - CX runs on a desktop PC, and I access everything via my Surface).

Obviously I could use something like YAC - which requires it's own library application, but I'm not keen on having two library apps.

As most readers can use embedded metadata, the file names likely aren't important - as long as they can be used to identify the sort order.

**Comment by mcpierce** [comment]
That really sounds like the need for another reader app, TBH. I've been careful to keep CX from becoming a reader (that's why I've removed the reading code from the details tab view) since I feel it would dilute the app too much.

**Comment by bareheiny** [comment]
We may be talking at cross-purposes here!

I'm thinking CX should have a bulk download / copy feature that would allow a user to copy an entire reading list (named in a way that could be used to identify the correct reading order).  The comics could then be accessed by an external reading application (such as CDisplayEX or Cover) which may, or may not, support OPDS.

Currently I do something similar with CR using the library organiser...then I have to manually flag the comics as read.

**Comment by mcpierce** [comment]
Possibly, though the bulk download would be the first option I mentioned previously (the archive download). I think a feature like that would be a perfect plugin as opposed to a core feature, since it's not really a library management feature but a feature to support reading outside of the app.

**Comment by bareheiny** [comment]
Came to the same conclusion over night.
