### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by kmccormi** [mcpierce/comixed#492]
I'ved tried to compile the environment but I keep running up against an error when the initial tests are running

The platform is Win 10 and all prerequisites are installed:
OpenJDK 12.0.2
NodeJS
Maven

I used git clone to create the install directory, then open a command prompt window (as admin) and navigated to the comixed directory. I then ran the command "mvn clean package", which then compiles and starts to run tests and then errors out at test 2 (the Library module)

I checked ownership for all directories referenced in the error and all seems okay. I tried deleting the install directory and starting over. I tried downloading the jar files to the install directory from the releases page - nothing.

The output from maven and the error is attached. 
[comixed mvn error.txt](https://github.com/mcpierce/comixed/files/3402428/comixed.mvn.error.txt)

Hope its something simple I've messed up on.

Thanks

**Comment by mcpierce** [comment]
Did you change any of the code locally, or was this a simple checkout and build attempt? Do you have OpenJDK 8 available? OpenJDK 12 should be able t build for 8, but I'm wondering if there might not be a chance in the compiler that might be causing the issue being reported about forking a process during the build.

**Comment by kmccormi** [comment]
Just a checkout and build. I'll see if I can find OpenJDK8 and try from there.

**Comment by kmccormi** [comment]
Removing OpenJDK 12 and replacing it with OpenJDK 8 did the trick. I still needed to separately install the JRE (don't know why) in order to get the jar file open, but all seems good for now. I'll close this out, and thanks for the help.

**Comment by bareheiny** [comment]
Would you mind letting me know where you found OpenJDK 8?

I'm running into simlar compile issues, and am wondering if they have the same cause - and I haven't had any luck finding OpenJDK 8 for windows.

**Comment by kmccormi** [comment]
I downloaded JDK 8 from RedHat - here: https://developers.redhat.com/products/openjdk/download

**Comment by bareheiny** [comment]
Cheers bud.  Sadly that didn't resolve my issue.

Eh, was worth a try though :)

**Comment by mcpierce** [comment]
https://github.com/ojdkbuild/ojdkbuild/releases

Though, TBH, I've hit build issues on WIndows. SPecifically, the comixed-tasks project can sometimes get weird when building due to the same problem you're seeing around forking processes. That's part of why I do all of my development on Mac.

```[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-12.0.1\bin\java" -javaagent:C:\\Users\\mcpie\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.1\\org.jacoco.agent-0.8.1-runtime.jar=destfile=C:\\Users\\mcpie\\Git\\comixed\\comixed-library\\target\\jacoco.exec -jar C:\Users\mcpie\AppData\Local\Temp\surefire14980886180373690661\surefirebooter17930237593071816345.jar C:\Users\mcpie\AppData\Local\Temp\surefire14980886180373690661 2019-07-20T06-12-04_803-jvmRun1 surefire1080655044449054188tmp surefire_013044883869258183133tmp"
[ERROR] Error occurred in starting fork, check output in log
```

**Comment by bareheiny** [comment]
Looks like my orginal issue was due to a lack of understanding of cloning and getting the code to be compiled.

Now I'm getting test failures similar to the original issue - regardless of what JDK I use (Oracle as linked in the main page, the Redhat version or one of the ojkbuild releases).

Going to put this in the "too hard" basket for now.

**Comment by mcpierce** [comment]
Yeah, the Windows JDKs are very odd when it comes to running concurrent tests, which are the core of the comixed-tasks project. I guess I'll need to revisit those tests and see if there's a better way to test how the Worker component (which performs all of the parallel tasks during imports, etc.) that doesn't break on Windows.

For now, you can skip the tests by running your build with:

```mvn clean install -DskipTests```

which will just build and install the JARs.
