### ISSUE TITLE
Source code zip file missing ".git" folder.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#496]
When getting the source code for compiling via a zip file ("Clone or download" button,  download zip), on unzipping the ".git" folder is not created.  Nor does it appear to be in the zip file.

This does not happen when using a "git clone" type command,

The ".git" folder created by "git clone" is hidden, and contains about 56MB of files.

The missing folder causes failures when attempting to compile the code - along the lines of "dot git folder not found".

**Comment by mcpierce** [comment]
That's how it works. The zip file is *only* the source code, and won't include repository data.

You would only get a .git directory if you clone the repository, since that directory holds all the metadata for the repository you're cloning.

**Comment by bareheiny** [comment]
Ah.

Not knowing anything about how git works, I assumed the folder was missing from the zip.
