### ISSUE TITLE
Cannot import a raw folder of comics

### ISSUE THREAD

**Issue by wyldphyre** [mcpierce/comixed#498]
**Describe the bug**
I have a folder of over 3000 comics (in subfolders) that I cannot import. I can search for an find them, and even select them, but I don't see any way to actually import them. I suspect this is because I don't have a CR database?

**To Reproduce**
1. Go to the Import page
2. Enter a folder that contains comics archives
3. Click the "Find Comics" button
4. Select some of the found comics
5. Now what? There is no way to proceed with the import 

I've tried the above in both Safari and Chrome on my Mac desktop, and in Chrome on the windows desktop that comixed is running on, with the same result.

**Expected behavior**
Once I have manually selected some comics, or used the "Select All" button to select everything found, I would expect to see an "Import" button or some other way to initiate the import.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.5 and Windows 10 Pro
 - Browser: chrome and, safari
 - Version: 0.4.0-20190728180804

**Comment by bareheiny** [comment]
The import process was changed a few builds back.

Once you've selected the comics for import, right click on a selected comic or the "Select all" button.  That gives you an import flyout menu.

**Comment by wyldphyre** [comment]
@bareheiny Ah. Good to know. Thanks for the info. That said, now I've used it a little, this is a super  janky way to navigate the UI. The only way to (apparently) drill into a comic is via a right click, and because of how navigation is handled I literally can't use the browser back feature to get out of the comic I just drilled into.
