### ISSUE TITLE
After opening a comic the browser back button doesn't work

### ISSUE THREAD

**Issue by wyldphyre** [mcpierce/comixed#499]
**Describe the bug**
When you select a comic and open it (from `Library` -> `Comics`) to see it's details, you cannot then use the browsers back button to get back to the previous page.

**To Reproduce**
1. Go to `Library` -> `Comics`
2. Right click a comic and choose `deselect all`
3. Click on a comic cover to select it
4. Right click on the selected comic and click on `Open comic...`
5. Once the comic has opened, click on the back button in the browser
6. You will be unable to navigate to the previous screen

**Expected behavior**
The back button should always be able to take you to the previous page you were on.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Browser: Chrome and Safari
 - Version 0.4.0-20190728180804

**Additional context**
If you use the browser history to navigate backwards to the second last page it *will* take you to the page you started on, but that is not a convenient thing to do, nor should it be necessary.

**Comment by mcpierce** [comment]
With single-page apps like CX, when you click on an element, you sometimes get more than one redirection; i.e., selecting a comic and clicking on the "Open" menu item will forward you to a page which then forwards you to another to display the data.

In the reproducer above, if you click on your browser's back button and look at the list of previous pages, they all have the same title. The one at the time will actually be a redirect, and the one before it (the second entry) is the actual library view page. If you select that second one, you will be shown the library as expected.  It's hard to differentiate them since (right now) all of the pages have the same title shown.

I've opened #504 to help make it clearer to the user when viewing page history what the pages are in their back history.

**Comment by wyldphyre** [comment]
What I'm getting from your explanation (and issue #504) is that you're just going to fix the page titles to make the multiple redirections more obvious? That doesn't solve the problem of being able to get back out of the comic.

**Comment by mcpierce** [comment]
That's correct. It's because the app can't make the back button jump back two URLs with one click. It's an unfortunate consequence of how SPA frameworks like Angular use redirects and forwards in their routing to move between views.

**Comment by wyldphyre** [comment]
(not a web dev but) that sounds like something that there must be a way to avoid?

Regardless, if the back button isn't going to work, could we maybe get a button in the UI to take us back out of the comic to where we were before? And ideally a button to open the comic as well.

I find navigating this UI to be slow and painful, and a lot of it is because there is no simple (or obvious) way to enter/exit screens or interact with a comics. Drilling into a comic requires multiple clicks (left, and often right as well to clear the persistent selection), and getting back out means bringing up the browser history and looking at it to work out which page I should be going back to.

**Comment by mcpierce** [comment]
A breadcrumb trail is something I've always had in mind for the UI, just hadn't gotten around to implementing it.

The UX experience was rewritten with this past release, so there's bound to be navigation issues. I'm open to any/all feedback and ideas on how we can evolve it to make it more intuitive.

**Comment by wyldphyre** [comment]
I hadn't considered a breadcrumb option, but that would probably do the job.

p.s. I feel like I should say that my recentl spate of bug issues and critique of the UI represent my hope for what Comixed could eventually be. I've long had a vague idea of producing a similar app, but between being lazy :) and not being familiar with web dev it's just never happened. Having now stumbled across something that plans to do what I had in mind (and more), I very much look forward to seeing how Comixed evolves. I may even have a go at contributing one day if the mood takes me, though I'm not a Java or Web dev (Delphi and C# mostly).

Cheers
