### ISSUE TITLE
Import with metadata often/typically doesn't use the CR xml data embedded in the archive

### ISSUE THREAD

**Issue by wyldphyre** [mcpierce/comixed#501]
**Describe the bug**
I imported a `.cbz` file (filename is `"Analog 001 (2018) (Digital) (Zone-Empire).cbz"`) with a embedded CR data (a `Comicinfo.xml` was in the archive) and despite the fact the series was specified in the xml data, Comixed imported the series as `Analog 001`, which looks like it came from the filename.

This import was done as part of a raw folder import, not a CR database import. The import was set to `with metadata`, so I would have expect it to use the embedded CR data. As far I can tell this problem occurred for roughly half of all the files I imported, during an import of ~3000 files. I can't see a reason why some worked and some didn't.

**To Reproduce**
1. Go to `Admin` -> `Import`
2. Fill in a folder known to contain files with embedded CR data and click on `Find Comics` 
3. Select a comic with embedded CR data
4. Right click on the selected comic and import used `with metadata`
5. Click on `Yes`
6. Locate the imported comic and look at the series. It will be based on the filename, instead of the embedded metadata

I did the following steps with a an archive called `Analog 001 (2018) (Digital) (Zone-Empire).cbz`, whose embedded data said its series was `Analog`, and the comic was imported with a series of `Analog 011`.

**Expected behavior**
If an comic archive contains an embedded ComicRack metadata xml file, then that metadata should be used to populate the imported comic.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.5 (desktop), Windows 10 (Comixed app)
 - Browser: Chrome and Safari
 - Version 0.4.0-20190728180804

**Comment by mcpierce** [comment]
Can you provide the ComicInfo.xml file from the comic in question? Also, were there any other fields that appeared to not be imported?

**Comment by wyldphyre** [comment]
I tried to upload the xml file when I logged the issue, but apparently Github doesn't accept xml files. I've attached it as a zip file.
[ComicInfo.xml.zip](https://github.com/mcpierce/comixed/files/3464889/ComicInfo.xml.zip)

With regards to not pulling in other details, I just checked and it didn't pull in any of the several credits listed, nor the comments/notes. I guess it essentially seems like it the archive was imported as if I'd chosen the `no metadata` option.

**Comment by mcpierce** [comment]
I added the ComicInfo.xml file you provided to a test comic and imported it. What I found is that the ComicInfo.xml file is missing the Volume tag.

For the other data, the ComicInfo adaptor doesn't import everything at the moment.

The tags it currently processed are the Publisher, Series, Volume, Title, Number, Summary, Notes, Year, Month, Web, PageCount, Characters, Teams and Locations data. All of which were found and imported.

**Comment by mcpierce** [comment]
I've pushed a fix for this that includes checking for all of the creator roles (Writer, Editor, Penciller, Colorist, Inker, Letterer, CoverArtist) and pulls them in. Please take a look at it (it's on the 0.4.0 release branch) and, if it fixes the issue, please close this ticket. Thanks.

**Comment by wyldphyre** [comment]
I just have the released app build installed at the moment. I don't see a new build so it will take me a little bit to get the build environment setup to test.

**Comment by wyldphyre** [comment]
Sorry, but this doesn't look like it helped with the Series problem. I cloned the repo, switch to "release/0.4.0" and used the build process to build and run a new jar file, and it doesn't appear to have changed anything. I even started with a fresh database.

When importing a couple of my "Analog" comics as test samples they were each given the Series of "Analaog 001" and "Analog 002", which looks like it came from the file name.

However, the Credits and Story info did import fine.

**Comment by mcpierce** [comment]
Ah, I see the issue. In AddComicWorkerTask the filename scraper is firing *after* the comic has been loaded and any ComicInfo.xml file data has been applied. I've reversed the order of those operations so that the scraping is done first.

**Comment by wyldphyre** [comment]
Great. Will test it after work.

**Comment by wyldphyre** [comment]
Import seems to respect the embedded metadata now.
