### ISSUE TITLE
When starting an import, it always reports an error even when it's a successful start.

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#523]
**Describe the bug**
Starting an import causes an error message to display on the browser, even though the import started successfully.

**To Reproduce**
1. Go to the import page.
1. Find and select comics to be imported.
1. Click the Import button and confirm you want to start.
1. An error message is shown saying, "Failed to start importing comic files."
   1. However, the import *DOES* start, despite the error message.

**Expected behavior**
A success message to be displayed.

**Screenshots**
<img width="388" alt="Screen Shot 2019-08-24 at 12 12 54 PM" src="https://user-images.githubusercontent.com/61601/63639965-8d3d1600-c668-11e9-9316-f0fa1d81593a.png">

**Comment by bareheiny** [comment]
I was just about to create a bug for this.

The error message disappears within seconds, and if  you're importing a large number of comics the IMPORTSTATE does begin to count down.
