### ISSUE TITLE
Add File Name to the library filters.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#525]
As a user, I would like to be able to search for a comic using the file name.

Currently I can only search by specific meta-data, which may not be populated in CX for the comic I am looking for.

In the current instance, I am trying to find out if a specific set of comics was actually imported, as file name match against the CX and CR databases indicates it wasn't, but CX appears to strip some characters from the file name when loading them.

For example a file named "A+X Vol.2002 #15..." is showing as "A X Vol.2002 #15..." in the H2 database.

**Comment by mcpierce** [comment]
@bareheiny Are you sure you want to close this feature request? I think it would be a useful one to have in the application.

**Comment by bareheiny** [comment]
For now, I don’t need this feature any longer.

If it’s  useful, or somebody else wants it the ticket can be reopened.

I may revisit them at some point, but for now I’ve closed all of my open tickets that are unassigned or don’t have a label.

**Comment by mcpierce** [comment]
@bareheiny Very good. I hope not assigning them to labels wasn't the cause for closing them. I've been trying to get things lined up into this release and the one after. And given that I'm seeing a few new people contributing, I'm hoping those other features will get picked up by contributors.

But, seriously, if it's a useful feature, please feel free to leave them open. I appreciate the ideas you bring to the table.

**Comment by bareheiny** [comment]
At the moment I'm trying to get things in order so I can get more useful information about the time it takes to load a library (once everything is fully imported).

Everything else is secondary (for me) hence the closing, as I won't be looking at scraping or searching if it takes hours to load the libary.
