### ISSUE TITLE
Special characters in file names are being removed or replaced by "?"

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#526]
On importing a number of comics, I have found that comics with special characters in the file name are being loaded into the H2 database with a slightly modified FILENAME field.

For example:

"Black September Vol.1995#∞ (September, 1995).cbz" is being imported as "Black September Vol.1995#? (September, 1995).cbz"

"A+X Vol.2002 #10 (September, 2013).cbz" is being imported as "A X Vol.2002 #10 (September, 2013).cbz"

"Lazarus - X +66 Vol.2017 #05 (November, 2017).cbz" is being imported as "Lazarus - X  66 Vol.2017 #05 (November, 2017).cbz"

I haven't checked, but I believe this may cause issues later on if a query / add on / action is preformed that relies on using the file name - for example an add-on that copies files from one location to another.

**Comment by mcpierce** [comment]
What version of the app were you using?

**Comment by bareheiny** [comment]
Good question...not sure.  I cloned and compiled it on Thursday the 29th.  Unfortunately I rename the files prior to running (so my bat will always work), so can't tell.

I can re-clone and compile again if needed.

**Comment by mcpierce** [comment]
I'm guessing it's likely fixed on develop since that branch is no longer trying to encode the filenames (which would likely have caused the "+" to get munged before sending).

**Comment by bareheiny** [comment]
Fixed along with #527.
