### ISSUE TITLE
No pages for imported comics

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#527]
Seems to be related to #526

On import, the comics that had "+" characters removed from the file name do not have any pages imported into CX.

This causes the libary to show "no image available" cover thumbnails, but also means that the CX library records do not have page thumbnails.

**Comment by mcpierce** [comment]
If it's only happening to files that also have special characters in the filename then mostly the file was never actually imported; i.e., CX created a record in the database for the bad filename and didn't actually process the real file.

I'll look into both of these at the same time. Can you tell me what very of the app you were using? I ask because, with 0.5.0, the way the import filenames are sent to the backend is different and is meant to avoid any kind of encoding problems like this. If you're using a previous release, the bug might already have been fixed.

**Comment by bareheiny** [comment]
I'm likely using a 0.4.x version - I don't recall seeing a 0.5 in the file name prior to renaming the files.

**Comment by mcpierce** [comment]
Right now only releases are being automatically built since I didn't want to flood things with development checkin builds. Are you able to checkout develop and build/verify the bug still exists there?

**Comment by bareheiny** [comment]
How would I go about doing that?

I use "git clone", then used "git branch" to see what was there...and only "develop" is listed.

**Comment by mcpierce** [comment]
1. git checkout develop
1. mvn clean install
1. cd comixed-app
1. mvn spring-boot:run

Though I opened #531 today to re-enable doing incremental development builds. This way non-developers, or people who just don't want to have to build the project to use it.

**Comment by bareheiny** [comment]
No luck on the mvn spring-boot:run side...keep getting build failures.

Probably best if I wait for the next release.

**Comment by mcpierce** [comment]
If the failure is consistently in the comixed-tasks project, you can just skip all tests with:

```mvn clean install -DskipTests```

Gut, that all said, I'm going to push my fix for #531 today so we can have develop builds again.

**Comment by mcpierce** [comment]
Okay, the develop branch is now building releases again. So right now the 0.5.0 release is building as 0.4.9-SNAPSHOT-${date}. 

Can you check and see if you're still seeing this bug in the snapshot build and, if it's fixed, close this ticket?

**Comment by bareheiny** [comment]
Cloned and compiled CX - unfortunately the issue is persisting.  The "A+X" file is showing as "A X" (file name displayed in the Overview pane), and there are no pages or cover thumbnail.

Build details:

Source Branch:  Develop
Built on:  Sep 2, 2019, 10:06:31 AM
Version:  0.4.9-SNAPSHOT
Commit Hash:  e0779ad39f2b7f45d08243b8737e7a7adf8238b5
Time Of Last Commit:  Sep 2, 2019, 7:32:39 AM

**Comment by mcpierce** [comment]
The build details are kind of odd: how do you have a build that's dated tomorrow at 10am? Are you from the future? 😄

**Comment by mcpierce** [comment]
Okay, there was a change for the backend, which was still trying to decode filenames even though they're no longer encoded. I used a test file locally and it work, so I'm pushing this fix.

When you can, please verify it.

**Comment by bareheiny** [comment]
> The build details are kind of odd: how do you have a build that's dated tomorrow at 10am? Are you from the future? 😄
Well, I generally prefer to think of others living in the past :P

Everything looks good now, closing bug.
