### ISSUE TITLE
Users can subscribe to the library via an ODPS feed

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#53]
Depends on #44 

As a comic reader, I'd like to download new comics when they're added to the library.

When a new comic is added to the library, the ODPS feed will be updated to contain the new comic file and its details.

## Acceptance Criteria
1. When a new comic is added to the library, an entry is added to the ODPS feed.
1. Users of ODPS enabled clients will be able to subscribe to the feed.
1. ODPS enabled clients will be able to download comics for reading.
1. When a comic is downloaded, it is marked as read for that user.

**Comment by casret** [comment]
OPDS in a bit more rich and seems to be more supported by the reader clients.  The one thing that neither gives you is a read acknowledgment, but I think in most workflows, you can mark it read when it is downloaded, or perhaps we could also store a downloaded flap.

**Comment by mcpierce** [comment]
I emailed briefly with the author of Chunky and he had suggested the same thing. It's definitely a feature we should add to support Chunky and other readers.
