### ISSUE TITLE
Next and previous navigation buttons - comics sorted incorrectly.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#533]
When using the navigation buttons in the Overview pane (#453), issue numbers appear to be treated as characters...resulting in the navigation going 1, 10, 11...2, 3.

I assume if the series went past 19 issues, the order would be 2, 20, 21 and so on.

*edited to remove the accidential linking to other issues from using the hash symbol in front of the numbers.

**Comment by mcpierce** [comment]
Sorry, didn't mean to close this. Please verify the bug is fixed when you can and close the ticket.

**Comment by bareheiny** [comment]
Looks good :)
