### ISSUE TITLE
Navigation buttons - rename "Last issue" button.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#534]
It's a minor issue, and largely semantic - but could the "Last Issue" button be re-labled to "Previous Issue"?

"Last Issue" would lead me to think the button was going to navigate to the last comic in the selected series, rather than the previous issue.

**Comment by mcpierce** [comment]
Please verify this fix when you can and close the ticket.

**Comment by bareheiny** [comment]
Looks good :)

Thanks for making that change.
