### ISSUE TITLE
Next and previous buttons - info tab reverting to "Overview"

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#535]
Not sure if this is a bug, or a feature request.

When using the "Previous Issue" and "Next Issue" buttons, the selected information tab (? not entirely sure what it's called) reverts to "Overview".  Ideally, the tab should remain the same...so if I'm looking at "Pages", the next / previous issue should also show "Pages".

Easy enough to replicate - open a comic, change the tab to anything other than "Overview" and press "Previous Issue" or "Next Issue" - the selected tab will revert to "Overview".

**Comment by mcpierce** [comment]
I believe this is fixed. Please verify it when you can and close this ticket if it works.

**Comment by bareheiny** [comment]
May be a day or so before I can check - CX is currently running a 50k import :)

**Comment by bareheiny** [comment]
Looks good - although the cover image isn't updating.

Will close this, and create another bug later, as I'm seeing some weird behaviour in a few other spots as well - and I'm not sure if it's this build or not.
