### ISSUE TITLE
Add a Story / Arc filter to the library page

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#536]
As a user, I would like to be able to search / filter for specific story arcs.

Although I can access the issues in an arc via the Story pane, I may not be able to recall an exact issue to use as a starting point.

**Comment by mcpierce** [comment]
There is already a story arc collection page. Is there a difference between the above and that page?

<img width="969" alt="Screen Shot 2019-09-16 at 8 46 17 AM" src="https://user-images.githubusercontent.com/61601/64959139-89af4000-d85e-11e9-9d6e-807a6076ffd3.png">

<img width="1675" alt="Screen Shot 2019-09-16 at 8 48 07 AM" src="https://user-images.githubusercontent.com/61601/64959240-b9f6de80-d85e-11e9-93fe-1b37ee26b915.png">

**Comment by bareheiny** [comment]
Of ffs.

Closing because as a user, I didn't look properly.
