### ISSUE TITLE
Large library slow to load.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#539]
Appreciate that there may still be work going on in this area, so please close if appropriate.

Large (~52k files) libraries seem to be extremely slow to load.  While the load seems to be quick to start with (the file count speedily increments in hundreds as expected), after the 10k mark or so it slows down significantly.

Unfortunately waiting for 30 minutes plus (conservatively) for a library to load before doing anything isn't really viable.

**Comment by bareheiny** [comment]
update:  after at least 1.5 hours with nothing else happening in the app (I'm waiting for a full library load before doing anything), 43,200 comics have been loaded...or 84.5% of the library.

**Comment by mcpierce** [comment]
Is this still the case with the new loading code in place for the 0.5 release?

**Comment by bareheiny** [comment]
I *think* so - running a develop branch, built on 9 Sep 2019.

The library is updating in increments of 100.  I'd guesstimate that I'm getting a load speed of 100 per second to start with, but it slows down once about 10k files have been loaded...and continues to slow until the entire library has loaded.

**Comment by bareheiny** [comment]
Will have a log from Chrome when the current library display finishes.

From what I've seen, the fetch of 100 comics can range from milliseconds to upwards of 10 seconds.

**Comment by mcpierce** [comment]
I suppose the cataloging could be moved to the backend. For now I might just disable the chart on the frontend to remove it as an issue. Since that only updates when you're on the home page, do things seemed to run faster, the same or slower if you go to the comics page?

**Comment by bareheiny** [comment]
Chrome doesn't want to co-operate - the dev tools window was closed when I checked this morning.

I did go to the library page, and the speed is the same - so likely isn't the chart refreshing.  Moving it to the backend could make it easier to add new summary options - such as year and so forth.

**Comment by bareheiny** [comment]
Haven't looked at this lately - I think it's still an issue, but need more data.

Closing for now - will either create a new bug / feature or re-open this once I get the time to look into it further.

**Comment by bareheiny** [comment]
Currently it's taking over 5 hours to load a library - probably longer but issue #585 is causing problems.

Note that for the purposes of defining a loaded library, I'm looking at the time from CX starting and my logging in to the "Total:" number to reflect the number of comics in the CX DB.

![Untitled](https://user-images.githubusercontent.com/1912425/68080265-9f071a80-fe5c-11e9-931a-16ebdff6bba0.png)
