### ISSUE TITLE
"Getting comic updates failed" spam.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#541]
After a library has loaded, I am getting a constant stream of "Getting comic updates failed" messages.

Due to the placement of the messages, and the fact that they seem endless, it is almost impossible to perform other actions in CX.

Screenshot for reference.  Note that the messages continuiously scroll...as the top one closes, and is replaced by a new one at the bottom.

![CX spam](https://user-images.githubusercontent.com/1912425/65095393-13a10980-da15-11e9-9c11-952c509d5e7e.png)

**Comment by mcpierce** [comment]
I'm planning to address this with #528. Or is this more about where the toasters show up on the screen?

**Comment by bareheiny** [comment]
The placement isn't great - but it's not an issue when the toasters disappear quickly.

The main problem is they seem almost endless at the moment.

**Comment by mcpierce** [comment]
Understood. So I'm going to close this ticket as #528 is for throttling the error toasters.
