### ISSUE TITLE
Database increasing in size for no apparent reason

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#542]
Following a successful full import of my comic library, I took a copy of the CX database.  

The copies size is 970MB.  After various starts and res-starts of CX to look into the library load times, I have noticed that the DB is now 2.97GB - even though no new records have been added.

There may be a rationale for this, but an increase of that size, for no apparent reason, doesn't seem quite right.

**Comment by mcpierce** [comment]
Can you zip that up and put it into Dropbox and email me the link? mcpierce@gmail.com

**Comment by bareheiny** [comment]
I deleted the 2.97GB DB, and restored the smaller.

After leaving CX running all day, the DB has not increased in size, so closing as unable to replicate.

**Comment by bareheiny** [comment]
Adding this for (possible) future reference:

https://github.com/h2database/h2database/issues/301
