### ISSUE TITLE
Question about updating reading lists via SQL.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#545]
Not really a feature request, or a bug...but I'm wondering about adding comics to reading lists via SQL.

I appreciate that this may be unexpected / undesired behaviour from a user...for now I'm just trying to directly meet my most pressing needs (creating a "smart" list containing all active series, and another of issues that need to be scrapped via CX, as well as importing a CR database into a temp table, then compares the page count and file names to the CX database etc.)

In theory, the reading list scripts seem pretty straight forward - access the CX database via a SQL client (in my case, I'm using SQuirreL), write some sql that inserts records into the READING_LIST_ENTRIES table and that's it.

Practically, this causes some odd behaviours:

1.  Attempting to open the reading list via the CX web interface takes me to the "New List" screen.
2.  The DB size increases dramatically (#542)

Am I missing something?  I wouldn't have expected the weird behaviour, and any guidence would be appreciated - although I fully appreciate you may tell me it's not supported use, and I'm on my own :)

**Comment by mcpierce** [comment]
Can you open the dev tools and see if there are any error messages shown in the console and if there are any non-200 responses on the network tab when you're accessing the reading lists?

**Comment by bareheiny** [comment]
Will check that later - just re-creating my test database.

A bit more information though:  The inserted reading lists are displayed in the reading list section, as is the appropriate number of comics on the list.

Creating a reading list via the CX frontend does not seem to trigger the same behaviour as the SQL inserted one.

**Comment by bareheiny** [comment]
This doesn't seem to be related to inserting reading lists via SQL, as I'm not able to reproduce the same behaviour (both the reading list, and increasing DB size) after creating reading lists via the front end.

I'm thinking it may be appropriate to close this, and create a new bug once I've nailed down the exact steps required to reproduce this.

It *looks* like it happens when I log out with an action still pending in the developer tools screen.  The login function stops working (even though the events show in dev tools).  A page refresh allows me to log in again, but also triggers the issues above.

**Comment by bareheiny** [comment]
Closing as this seems to be a reading list issue, rather than the method for creating reading lists.
