### ISSUE TITLE
Is there a way to capture all CX logs - some only show in the command line.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#551]
I'm running CX from a bat script, and have noticed that errors are occasionally output to the CMD window rather than the CX log (I'm running CX with --logging.level.org.comixed=DEBUG).

The errors shown in the cmd window are usually of the "javax.imageio.IIOException: Unsupported JPEG process" type, but without more logging (such as time stamps etc.), I cannot attempt to determine what is triggering the error.

Note that the comics in my test library loaded fine with no image errors at all.

**Comment by mcpierce** [comment]
That sounds like some output from one of the dependencies, which unfortunately we have no control over. All of the logging in the CX code is captured with Log4J so we can redirect all of it to log files as you describe.

That said, you can redirect stdout in your batch file to a file to capture it. Though you won't be able to get timestamps in it.

**Comment by bareheiny** [comment]
Closing as answered.
