### ISSUE TITLE
Add user button missing from Admin / user pane.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#555]
As per heading - the add user button is missing from the menu pane

See attached image.
![CX admin menu](https://user-images.githubusercontent.com/1912425/66175403-ff683800-e6b5-11e9-8666-d92b591cc2e3.PNG)

**Comment by mcpierce** [comment]
@bareheiny Try out the next build and, if it fixes the issue, please close this ticket.

**Comment by bareheiny** [comment]
The button is now there, but I cannot create a new user.

**Comment by mcpierce** [comment]
Yeah, that's a separate bug that's popped up on the develop branch.

**Comment by bareheiny** [comment]
Closing as initial issue has been resolved (add user button now accessible).

**Comment by mcpierce** [comment]
I just merged changes for #558 that should solve the other problem you were hitting with creating users. I've moved all of the user administration code into a new Angular module and partitioned it, as well as updating the backend to be more robust.
