### ISSUE TITLE
"Failed to complete task" notifications in log.

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#564]
During the second part of an import (where CX does the heavy lifting and creates page hashes etc.), a number of "Failed to complete task:  Process entry task [FILE PATH & NAME]" lines are being written.

These seem to be preceeded by another erorr "Value too long for column "TITLE VARCHAR(128)...".

I cannot tell if these errors actually indicate a failure of some sort, of if they're purely informative - however they are showing as both an error and a warning.

**Comment by bareheiny** [comment]
Possibly slightly more concerning that I originally anticipated.

"Z:\Comics\Acclaim\Bloodshot [1997]\Bloodshot Vol.1997 #13 (March, 1998).cbz" has 2,359 "Entry found for:" lines in my CX log.

It looks like CX processes the comic, then the delete record fails, so the comic is selected for processing again ad nauseum.

[CX selected log.txt](https://github.com/mcpierce/comixed/files/3726824/CX.selected.log.txt)

**Comment by mcpierce** [comment]
Yeah, that's definitely a bug. I guess I didn't make the title field long enough in the new database migration, so I'll need to fix that. Also need to adjust how the process records are handled so that we don't get stuck in a processing loop.

**Comment by mcpierce** [comment]
I've pushed what I hope is a change that should fix this. The worker will remove the process task whether it succeeds or not. I also adjusted the migrations to to make the fields much wider so that we'll (hopefully) have no more cases where the data's too big for the column. But we'll see.

If this works, please close the ticket. And thanks for reporting the bug.

**Comment by bareheiny** [comment]
Trying it now.

I had to delete my existing db, as the log file was filling up with errors.  Is that expected (the having to recreate the db part, not the errors in the log)?

**Comment by mcpierce** [comment]
No, deleting your DB was only necessary because I changed one of the migrations. I wouldn't have done that if it was in a release, but since it's only on develop it's okay.

**Comment by bareheiny** [comment]
Not seeing any sign of the issue now, and the processing as gotten past the point where it was failing yesterday.

I can close the issue now, or leave it until all issues have finished importing - sometime after 48 hours or so based on previous imports.

**Comment by mcpierce** [comment]
Okay. Are you running just this fix, or the do you also have the code form #510 as well? If the latter then I'm hoping you'll be able to confirm that the import is vastly improved as well.

**Comment by bareheiny** [comment]
It looks like I only have that fix, but have stopped CX and am getting a new build ready now.

**Comment by bareheiny** [comment]
About 2.3k comics into the second part of the import process:

Exception in thread "Jarvis-ComiXed" java.lang.OutOfMemoryError: Java heap space

**Comment by mcpierce** [comment]
Not sure I follow. You have a 1.5G comic? The largest in my library I could find is 54M. How many pages does this comic have?

**Comment by bareheiny** [comment]
Going to close this one, as the orginal issue appears to have been resolved.

Will create a new bug for the memory issue.
