### ISSUE TITLE
OutOfMemoryError causing CX to fail when processing large comics

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#567]
CX (started via command line) throws an OutOfMemory error when attempting to import extremely large files.

This is likely the same issue raised in #259, and is definitely the same as #473.  Prior to the most recent builds that break the import process into two stages, increasing the maxium amount of memory available for CX to 2GB solved the problem (java **-Xmx2g** -jar comixed-app.jar).

Note that the 2GB was an arbitrary number...although I suspect it is about right, as I'm thinking the amount of memory required would be the size of the largest file in a library + a bit for overhead.

In the most recent build (eb9691a), the memory issue has appeared again - even though I am still setting the maxium availabe as 2GB.

My library has 11 files that are over 900MB, with the largest topping out at 1.61GB.  These are all trades / collected editions, with between 439 to 692 pages - and the memory issue appears to occur when processing beings on these files.

For now, I have moved them to directory that won't be processed by CX.

**Comment by bareheiny** [comment]
After around 4 hours of processing, the out of memory issue occured again - while / after processing a 810MB, 369 page comic.

**Comment by bareheiny** [comment]
Split some files out - imported a 50MB, 100MB, 104MB, 202MB, 223MB, 301MB, 362MB, 400MB, 515MB and a 611MB file...no problems.

Import failed on a 1.6GB file...somewhere around page 400 or so.

**Comment by mcpierce** [comment]
Thinking about this, my proposed strategy is to combine the fix for this with the image caching ticket (#144), the import process shouldn't try to load all comic pages into memory (which is how it does it now). Instead, it should just extract the image to its cached position, take it's metrics, and move on to the next file.

**Comment by bareheiny** [comment]
Sounds like a solid plan - and would pre-empt issues arising for users who either have low memory machines, or who wouldn't know how to manually increase the memory available.

For now, I've moved files > 800MB from my main comic directory.

**Comment by mcpierce** [comment]
This appears to be fixed in my testing environment. I just removed the content as a field on Page and instead only have Page know about the content when it's initially created during import; i.e., give it the content, let it generate the hash and image metrics, and then it discards the content.

I created a 1.5G comic with 901 images and it imported them without blowing up. Each image is about 100-200k in size. I'll commit that change to this ticket and you can verify it works, and I'll do the page caching separately.

**Comment by bareheiny** [comment]
Unfortunately CX is still choking on the larger files.

Not sure if it's relevant, but the images in the file range from 395KB to 8.7MB...with most being in the 3MB to 4MB range.

**Comment by mcpierce** [comment]
@bareheiny Got it.

**Comment by mcpierce** [comment]
@bareheiny I was able to import the comic without issue. Are you certain you tested with a build containing the fix?

**Comment by bareheiny** [comment]
I thought I was - the build is 13bae19.

Currently compiling a new version from source, so will give it a try again today.

**Comment by bareheiny** [comment]
Still failing unfortunately - build 7d51d2d.

If you were able to import it, it must be something at my end.  I'll try another machine later and see if I can figure out what's going on.

**Comment by bareheiny** [comment]
Any thoughts as to how I can track down what's causing the heap spike?

![2019-10-21](https://user-images.githubusercontent.com/1912425/67168814-2b005780-f404-11e9-9414-23bb90616c6a.png)

**Comment by mcpierce** [comment]
@bareheiny If you remove just that one comic from the database (might have to manually do it as there's a bug around deleting comics), you can turn on all logging for CX and try importing it again and see what happens. The Page class no longer holds onto the data, which is what was sucking up the memory, so I'm really confused and wondering what's going on.

**Comment by bareheiny** [comment]
@mcpierce, yeah it's really, really weird...and I'm honestly surprised you didn't strike this when importing the comic (and this has only started happening since the import was split into two stages - prior to that, I was able to import my entire library with no issues).  Any chance your default max memory is set higher than 2GB by default?

Anyways, the charts above were taken when CX ran with a fresh database...the only thing that was done was to attempt to import the comic.

I log by default (--logging.level.org.comixed=DEBUG > z:\comiXed.log).  I've been watching the logs, and it looks like every page in the comic has a hash generated, and then the archive is closed...the memory spike / failure appears to happen almost immediately after the archive is closed - when the "Setting comic file details" line is written to the log.

**Comment by mcpierce** [comment]
Doh!

At that spot is the comic processor attempts to take a hash of the comic file. It should be using it as a stream, but it's instead using a byte array.

I'll fix that today.

😊

**Comment by mcpierce** [comment]
@bareheiny Just pushed a fix on this that should solve the memory spike problem. Please let me know if it works for you.

**Comment by bareheiny** [comment]
Looks good!  The comic loaded with the default max memory amount as well :)

I'm going to try a full load now, and will see what happens.  If that goes well, I'll close the ticket.

Fair warning though, I've noticed a few more things I need to create tickets for - once I've got a complete library, I'll start documenting those.  Nothing serious, just minor polishing type things :)

**Comment by mcpierce** [comment]
Excellent! after you test please close this ticket if we’re good to go.
-- 
Sent from Gmail Mobile

**Comment by bareheiny** [comment]
After 47 hours of importing, no memory issues have occured - with no increase to the max memory available, CX is comfortably working with 1GB.

Closing this, as the import will have processed a number of large files - so any future failure likely won't be to the import process.
