### ISSUE TITLE
What is required to run, not build?

### ISSUE THREAD

**Issue by PiDockMedia** [mcpierce/comixed#602]
Assuming one grabs a pre-compiled release .jar file and does not build comiXed, what are the minimum software requirements? JDK8 ans a web browser, obviously. I assume Node.js?. Are Maven and Yarn prereqs? Anything else?

Again, not to build, just to run the .jar file and hit it on port 7171 and have everything work.

**Comment by mcpierce** [comment]
The only thing you need is a browser and Java8 or later.

Node.js, Maven and Yarn are build requirements only.

**Comment by mcpierce** [comment]
Didn't mean to close this. If that answers your question, please feel free to close the ticket.

**Comment by PiDockMedia** [comment]
Perfect! Thanks!
