### ISSUE TITLE
What is the actual current release?

### ISSUE THREAD

**Issue by PiDockMedia** [mcpierce/comixed#612]
Is 0.3.0 the actual current "release" version. Is there a 0.4.0 that is stable and working? I picked the latest 0.4.0 and it is having a few issues for me. I'd like to run a stable version to start organizing my collection until 0.5 is out. I would also like to make sure the docker container installed as the "latest" is the latest stable usable version.

**Comment by mcpierce** [comment]
With the change from FlywayDB to Liquibase done during 0.5 development, I wouldn't recommend using 0.4 as the stable release. It can be used as a preview, but that change will require deleting and rebuilding your database.

I would say that the current 0.5 development stream can be used if you want to start managing your code, and we could bundle it as a pre-release.

**Comment by PiDockMedia** [comment]
I'll give that a try. Is the zip file the new format with paths you can depend on going forward? The current docker image assumes a .jar but I'll reconstruct with an unzip if it makes sense to.

**Comment by mcpierce** [comment]
The top-level directory of the archive right now is the release version:
```
21:08 $ unzip -l *zip
Archive:  comixed-app-0.4.9-SNAPSHOT-20191119062947.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  11-19-2019 06:30   comixed-app-0.4.9-SNAPSHOT/
        0  11-19-2019 06:30   comixed-app-0.4.9-SNAPSHOT/bin/
    35141  09-24-2019 20:25   comixed-app-0.4.9-SNAPSHOT/LICENSE
    12637  09-24-2019 20:25   comixed-app-0.4.9-SNAPSHOT/RELEASE.md
     7560  09-24-2019 20:25   comixed-app-0.4.9-SNAPSHOT/QUICKSTART.md
      320  11-15-2019 22:01   comixed-app-0.4.9-SNAPSHOT/CONTRIBUTORS.md
     8573  11-15-2019 21:34   comixed-app-0.4.9-SNAPSHOT/README.md
 55964708  11-19-2019 06:29   comixed-app-0.4.9-SNAPSHOT/bin/comixed-app-0.4.9-SNAPSHOT.jar
     2451  11-09-2019 18:59   comixed-app-0.4.9-SNAPSHOT/bin/run.bat
     2265  11-09-2019 18:59   comixed-app-0.4.9-SNAPSHOT/bin/run.sh
---------                     -------
 56033655                     10 files
```
But that can be changed if it makes things easier for Docker.

**Comment by PiDockMedia** [comment]
I think it looks great. I'll put in some extract and cleanup logic.
