### ISSUE TITLE
The user can select all comics for import

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#72]
As a library owner, I'd like to select all comics found for import and bring them all into the library.

When more than one comic file is presented for import, a button is shown above the comics' **Select** button labeled **Select All**. When I press this button, all of the comics presented are selected and their **Select** buttons are hidden and the **Deselect** button is shown.

Individual comics can then be deselected. Hitting the **Select All** button again would select all comics again.

## Acceptance Criteria
1. When there are more than one comic to import, a **Select All** button is presented above the other select buttons.
1. Pressing the **Select All** button selects all comics.
   * All **Select** buttons become **Deselect** buttons.
1. Deselecting a single comic deselects only that comic.
   * Pressing **Select All** again reselects all deselected comics.

**Comment by bareheiny** [comment]
Is this in 0.3.9?

I'm not seeing an "Import All" button on the import page.

**Comment by mcpierce** [comment]
It was, but then it was removed when the library display code was refactored to be reusable. The old code had a very clumsy way of selecting comics, so I rewrote it from the ground up and haven't re-implemented this feature yet.
