### ISSUE TITLE
Run Angular testing

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#80]
We need to run the unit tests for the Angular codebase under web-frontend.

**Comment by awe247** [comment]
Hi, I wanted to update the spec tests to account for changes I made to the alert messages but I'm having issues running them with much success. Is there a trick to this or do they need some updating? If that's the case, I'm happy to try and get them running. I just don't want to make too many changes and then find out I was attempting to run them incorrectly.

Although, it's probably my system? I'm running with...
angular 1.7.4
karma 3.1.0
jasmine 3.2.0
